version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    restart: always

  bytebase:
    image: bytebase/bytebase:latest
    container_name: bytebase
    ports:
      - "5678:8080"
    volumes:
      - bytebase-data:/var/opt/bytebase
    restart: always

volumes:
  clickhouse-data:
  bytebase-data:
