version: '3.8'

services:
  clickhouse_source:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse_source
    environment:
      CLICKHOUSE_DB: db1
    ports:
      - "9001:9000"
    volumes:
      - clickhouse_source_data:/var/lib/clickhouse
      - ./clickhouse_init_source/create_user.sh:/docker-entrypoint-initdb.d/create_user.sh
    healthcheck:
      test: ["CMD", "clickhouse-client", "--host", "localhost", "--query", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 15
    networks:
      - shared_data_pipeline_network

  clickhouse_destination:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse_destination
    environment:
      CLICKHOUSE_DB: db2
    ports:
      - "9002:9000"
    volumes:
      - clickhouse_destination_data:/var/lib/clickhouse
      - ./clickhouse_init_dest/create_user.sh:/docker-entrypoint-initdb.d/create_user.sh
    healthcheck:
      test: ["CMD", "clickhouse-client", "--host", "localhost", "--query", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 15
    networks:
      - shared_data_pipeline_network
    
  data_generator:
    container_name: data_generator
    build: ./data_generator
    depends_on:
      clickhouse_source:
        condition: service_healthy 
    environment:
      CLICKHOUSE_HOST: clickhouse_source
      CLICKHOUSE_PORT: 9000
      CLICKHOUSE_DB: db1
      CLICKHOUSE_USER: airflow
      CLICKHOUSE_PASSWORD: airflow_password
    restart: always
    networks:
      - shared_data_pipeline_network

volumes:
  clickhouse_source_data:
  clickhouse_destination_data:

networks:
  shared_data_pipeline_network:
    external: true