version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - datalake

  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_SUBMIT_OPTIONS=--packages org.apache.iceberg:iceberg-spark-runtime-3.3_2.12:1.4.2
      - HOME=/home/spark
    ports:
      - "7077:7077"
      - "8088:8080"
    volumes:
      - ./spark-home-master:/home/spark
    networks:
      - datalake
    depends_on:
      - minio

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_SUBMIT_OPTIONS=--packages org.apache.iceberg:iceberg-spark-runtime-3.3_2.12:1.4.2
      - HOME=/home/spark
    volumes:
      - ./spark-home-worker:/home/spark
    depends_on:
      - spark-master
    networks:
      - datalake

  trino:
    image: trinodb/trino:latest
    container_name: trino
    ports:
      - "8080:8080"
    volumes:
      - ./conf/catalog:/etc/trino/catalog
      - trino_data:/var/trino/data
      - ./hadoop/core-site.xml:/etc/hadoop/conf/core-site.xml:ro
    environment:
      - HADOOP_CONF_DIR=/etc/hadoop/conf
    networks:
      - datalake
    depends_on:
      - minio

  # kylin:
  #   image: apachekylin/apache-kylin-standalone:5.0.0-GA
  #   container_name: kylin
  #   ports:
  #     - "7070:7070"
  #   environment:
  #     - KYLIN_HOME=/opt/kylin
  #   volumes:
  #     - kylin_data:/opt/kylin
  #   networks:
  #     - datalake

volumes:
  minio_data:
  # kylin_data:
  trino_data:

networks:
  datalake:
    driver: bridge
