FROM bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8

COPY utils/init-hdfs.sh /init-hdfs.sh
COPY utils/start-namenode.sh /start-namenode.sh
RUN chmod +x /init-hdfs.sh /start-namenode.sh

ENTRYPOINT ["/start-namenode.sh"]
