apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Frontend</title>
    </head>
    <body>
      <h1>Hello from Frontend!</h1>
      <div id="response"></div>
      <script>
        fetch('/api')
          .then(response => response.json())
          .then(data => {
            document.getElementById('response').textContent = JSON.stringify(data);
          })
          .catch(err => {
            document.getElementById('response').textContent = 'Error: ' + err;
          });
      </script>
    </body>
    </html>
