apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: frontend-content
          mountPath: /usr/share/nginx/html
        - name: frontend-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: frontend-content
        configMap:
          name: frontend-html
      - name: frontend-config
        configMap:
          name: frontend-nginx-config
