version: '3.8'

services:
  spark-master:
    image: bitnami/spark:3.4
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      # - SPARK_RPC_AUTHENTICATION_ENABLED=no
      # - SPARK_RPC_ENCRYPTION_ENABLED=no
      # - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      # - SPARK_SSL_ENABLED=no
    ports:
      - "7077:7077"
      - "8080:8080"

  spark-worker:
    image: bitnami/spark:3.4
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    ports:
      - "8081:8081"

  spark-shell:
    image: bitnami/spark:3.4
    container_name: spark-shell
    depends_on:
      - spark-master
    environment:
      - HOME=/tmp
    volumes:
      - ./jars:/opt/bitnami/spark/user-jars
    entrypoint: [ "tail", "-f", "/dev/null" ] # Keep the container running for exec
